### ISSUE TITLE
Kubernetes setup

### ISSUE THREAD

**Issue by ThomasCardin** [ThomasCardin/homelab#1]
## Summary

Ensure that all aspects of the cluster are covered with a stable and reliable solution

## TODO

- Storage
    - [x] Rook ceph
- Networking
    - [x] Cilium 
    - [x] External DNS
- Updates
    - [x] Renovate
    - [ ] ... 
- CI/CD
    - [x] ArgoCD / Kustomize
- Monitoring
    - [x] Grafana
    - [x] Grafana Tempo
    - [x] Grafana Loki
    - [x] Grafana Mimir
    - [x] OpenTelemetry
    - [x]  kube-prometheus-stack
    - [x] Enable dashboard for cilium (operator, agent and hubble-relay)
    - [x] Enable dashboard for rook-ceph
    - [x] Enable a general Kubernetes dashboard
    - [ ] Uptime Kuma inside GCP
- Alerts
    - [x] Prometheus AlertManager
    - [ ] Robusta
- IaC
    - [x] Terraform
    - [x] Ansible
    - [x] Atlantis
- Security
    - Secrets
        - [x] X with ArgoCD
    - Certificates
        - [x] Cert-manager
     - Cloudflare Zero Trust
         - [x] Github authentication
         - [x] Application WAF using Github authentication (with Terraform)
    - [x] Oauth2-proxy
    - [ ] Auhentik
- Client application
    - [x] Migrate previous trilium-notes database to this cluster 
    - [x] Deploy Plex
- Chaos engineering
    - [x] Litmus
